[package]
name = "randomizer"
version = "0.1.0"
authors = ["Petko <pavlovskipetko@abv.bg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", default-features = false }
rand = "0.8.0"
